Data = read.csv("~/Documents/Assignment1/data raw/raw_yield_data.csv")
View(Data)
print("Work stage 1 completed")
clean_yield_data = na.omit(Data[Data$Frailty != "N" ,])
View(clean_yield_data)
write.csv(clean_yield_data,"~/Documents/Assignment1/data clean/clean_yield_data.csv")
print("Work stage 2 completed")